apps/felt/web/router.ex
defmodule Felt.Router do
  use Felt.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Felt.Auth, repo: Felt.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Felt do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/tables", Felt do
    pipe_through [:browser]#, :authenticate_user]

    get "/play", TableController, :play
  end

  # Other scopes may use custom stacks.
  scope "/api", Felt do
    pipe_through :api
  end
end

apps/felt/lib/felt/endpoint.ex
defmodule Felt.Endpoint do
  use Phoenix.Endpoint, otp_app: :felt

  socket "/socket", Felt.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :felt, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_felt_key",
    signing_salt: "zgI/NW3g"

  plug Felt.Router
end

apps/felt/lib/felt/repo.ex
defmodule Felt.Repo do
  use Ecto.Repo, otp_app: :felt
end

apps/felt/web/models/user.ex
defmodule Felt.User do
  use Felt.Web, :model

  schema "users" do
    field :username, :string
    field :password, :string, virtual: true
    field :password_hash, :string

    timestamps
  end

  def changeset(model, params \\ :empty) do
    model 
    |> cast(params, ~w(username), [])
    |> validate_length(:username, min: 3, max: 20)
  end

  def registration_changeset(model, params) do
    model
    |> changeset(params)
    |> cast(params, ~w(password), [])
    |> unique_constraint(:username)
    |> validate_length(:password, min: 6, max: 100)
    |> put_pass_hash
  end

  defp put_pass_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
      _ ->
        changeset
    end
  end

end

apps/felt/web/controllers/page_controller.ex
defmodule Felt.PageController do
  use Felt.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

apps/felt/web/controllers/session_controller.ex
defmodule Felt.SessionController do

  use Felt.Web, :controller

  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => %{"username" => user, "password" => pass}}) do
    case Felt.Auth.login_by_username_and_pass(conn, user, pass, repo: Repo) do
      {:ok, conn} ->
        conn
        |> redirect(to: table_path(conn, :play))
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> Felt.Auth.logout(nil)
    |> put_flash(:info, "You have been logged out")
    |> redirect(to: page_path(conn, :index))
  end

end

apps/felt/web/controllers/table_controller.ex
defmodule Felt.TableController do
  use Felt.Web, :controller

  def play(conn, _params) do
    render(conn, "play.html")
  end

end

apps/felt/web/controllers/user_controller.ex
defmodule Felt.UserController do
  use Felt.Web, :controller
  alias Felt.User

  plug :authenticate_user when action in [:index, :show]

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.registration_changeset(%User{}, user_params)
    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> Felt.Auth.login(user)
        |> put_flash(:info, "#{user.username} created!")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    render(conn, "show.html", user: user)
  end

end

apps/felt/web/views/error_view.ex
defmodule Felt.ErrorView do
  use Felt.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

apps/felt/web/views/layout_view.ex
defmodule Felt.LayoutView do
  use Felt.Web, :view
end

apps/felt/web/views/page_view.ex
defmodule Felt.PageView do
  use Felt.Web, :view
end

apps/felt/web/views/session_view.ex
defmodule Felt.SessionView do
  use Felt.Web, :view
end

apps/felt/web/views/table_view.ex
defmodule Felt.TableView do
  use Felt.Web, :view
end

apps/felt/web/views/user_view.ex
defmodule Felt.UserView do
  use Felt.Web, :view
end

apps/felt/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible"”" content="”"IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  
    <title>Vegas</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" id="cont">
      <div class="header">
        <ol class="breadcrumb text-right">
          <%= if @current_user do %>
            <li><%= @current_user.username %></li>
            <li>
              <%= link "Log out", to: session_path(@conn, :delete, @current_user),
                                  method: "delete" %>
            </li>
          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Log in", to: session_path(@conn, :new) %></li>
          <% end %>
        </ol>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>


    </div> <!-- /container -->
    <script>window.userToken = "<%= assigns[:user_token]%>"</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/felt/web/templates/page/index.html.eex
<h2>Welcome to Vegas</h2>

<p>Please login or register to play.</p>

apps/felt/web/templates/session/new.html.eex
<h1>Login</h1>

<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= submit "Log In", class: "btn btn-primary" %>
<% end %>

apps/felt/web/templates/table/play.html.eex
<!-- inject the logged in user info into the page -->
<%= content_tag :div, id: "vegas",
  data: [id: @current_user.id, name: @current_user.username] do %>
<% end %>

<div id="elm-container"></div>

<!-- <script src="<%= static_path(@conn, "/js/table.js") %>"></script> -->

apps/felt/web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :username, class: "control-label" %>
    <%= text_input f, :username, class: "form-control" %>
    <%= error_tag f, :username %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= text_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

apps/felt/web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.username %></td>

      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new) %>

apps/felt/web/templates/user/new.html.eex
<h2>New user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :create) %>

<%= link "Back", to: user_path(@conn, :index) %>

apps/felt/web/templates/user/show.html.eex
<h2>Show user</h2>

<ul>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>Password:</strong>
    <%= @user.password %>
  </li>

</ul>

<%= link "Edit", to: user_path(@conn, :edit, @user) %>
<%= link "Back", to: user_path(@conn, :index) %>